@startuml
|Kunde|
start
:Bruger åbner hjemmesiden;


:Bruger vælger bund, topping og antal;

:Bruger trykker "Læg i kurv";
:Bruger trykker "ordre";
:Vis kurvens indhold;
:Bruger trykker "bestil";
if (Er bruger logget ind?) then (ja)
|System|
  :Ordre bliver sendt til databasen;
  |Kunde|
else (nej)
if(Bruger har konto) then (ja)
  :Bruger logger ind;
  else(nej)
  :Bruger trykker "opret konto";
  |System|
  :Konto bliver sendt til databasen;
  |Kunde|
  :Bruger logger ind;
  :Bruger trykker "bestil";
endif
|System|

:Gemmer ordre;
:Sender ordre til bageri;

|Admin (medarbejder)|
:Logger ind i admin;
:Trykker "ordre";
:Ser brugere og deres ordrer;
:Vælger ordre;
:Forbereder cupcakes;

stop
@enduml